export const SOURCE_EXCERPT = {
    source: {
        memory_id: 'm1',
        state: 'ok',
        ticket_id: 't9',
        number: '000009',
        cycle_no: 1,
        closed_at: '2026-03-01T09:00:00Z',
        problem: 'Двойное списание за месяц',
        solution: 'Возврат второго списания после сверки',
    },
    messages: [
        {
            id: 'src1',
            seq: 3,
            author_type: 'client',
            author_name: null,
            text: 'Деньги списались два раза.',
            created_at: '2026-03-01T07:00:00Z',
            delivery_state: 'received',
            deleted: false,
            revision: 1,
        },
        {
            id: 'src2',
            seq: 4,
            author_type: 'staff',
            author_name: 'Борис Иванов',
            text: 'Оформили возврат второго платежа, деньги вернутся за 3 дня.',
            created_at: '2026-03-01T08:00:00Z',
            delivery_state: 'delivered',
            deleted: false,
            revision: 1,
        },
    ],
    attachments: [],
    highlight: ['src2'],
    truncated: true,
};
